// CONFIG
export const GET_CONFIG = "GET_CONFIG";
export const GET_CONFIG_PROCESS = "GET_CONFIG_PROCESS";
export const GET_CONFIG_SUCCESS = "GET_CONFIG_SUCCESS";
export const GET_CONFIG_FAILURE = "GET_CONFIG_FAILURE";

export const SAVE_CONFIG = "SAVE_CONFIG";
export const SAVE_CONFIG_PROCESS = "SAVE_CONFIG_PROCESS";
export const SAVE_CONFIG_SUCCESS = "SAVE_CONFIG_SUCCESS";
export const SAVE_CONFIG_FAILURE = "SAVE_CONFIG_FAILURE";

export const GET_CONFIGS = "GET_CONFIGS";
export const GET_CONFIGS_PROCESS = "GET_CONFIGS_PROCESS";
export const GET_CONFIGS_SUCCESS = "GET_CONFIGS_SUCCESS";
export const GET_CONFIGS_FAILURE = "GET_CONFIGS_FAILURE";

export const REFRESH_CONFIGS = "REFRESH_CONFIGS";
export const REFRESH_CONFIGS_PROCESS = "REFRESH_CONFIGS_PROCESS";
export const REFRESH_CONFIGS_SUCCESS = "REFRESH_CONFIGS_SUCCESS";
export const REFRESH_CONFIGS_FAILURE = "REFRESH_CONFIGS_FAILURE";

export const REFRESH_CONFIG = "REFRESH_CONFIG";
export const REFRESH_CONFIG_PROCESS = "REFRESH_CONFIG_PROCESS";
export const REFRESH_CONFIG_SUCCESS = "REFRESH_CONFIG_SUCCESS";
export const REFRESH_CONFIG_FAILURE = "REFRESH_CONFIG_FAILURE";

export const CLEAR_CONFIG = "CLEAR_CONFIG";
